[package]
name = "state_zome"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hdk = "0.5.6"
holochain_serialized_bytes = "0.0.56"

[profile.release]
opt-level = "z"
lto = true
