[package]
name = "metrics_zome"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = "0.5.6"
serde = { version = "1", features = ["derive"] }
holochain_serialized_bytes = "0.0.56"

[profile.release]
opt-level = "z"
lto = true
